import { AppTranslations, Language } from './types';

export const CHECKIN_TIMEOUT_WARNING = 24 * 60 * 60 * 1000;
export const CHECKIN_TIMEOUT_ALERT = 48 * 60 * 60 * 1000;

export const SHOP_ITEMS = [
  { id: 'ghost', nameEn: 'Ghost Mode', nameUa: 'Режим Привида', price: 500, icon: '👻', descEn: 'Hide status from others', descUa: 'Приховати статус від інших' },
  { id: 'extended', nameEn: '72h Window', nameUa: 'Вікно 72г', price: 1000, icon: '⏳', descEn: 'Alert friends after 72h', descUa: 'Тривога через 72г' },
  { id: 'gold', nameEn: 'Gold Profile', nameUa: 'Золотий Профіль', price: 300, icon: '✨', descEn: 'Animated golden border', descUa: 'Анімована золота рамка' },
  { id: 'guardian', nameEn: 'AI Guardian', nameUa: 'AI Охоронець', price: 600, icon: '🛡️', descEn: 'Daily AI safety tips', descUa: 'Щоденні поради від ШІ' },
  { id: 'animated', nameEn: 'Animoods', nameUa: 'Анімудзи', price: 400, icon: '🕺', descEn: '3D animated moods', descUa: '3D анімовані настрої' },
  { id: 'map', nameEn: 'Safety Map', nameUa: 'Карта Безпеки', price: 800, icon: '🗺️', descEn: 'Visual heat-map of friends', descUa: 'Візуальна карта друзів' },
  { id: 'priority', nameEn: 'Priority Alerts', nameUa: 'Пріоритет', price: 750, icon: '🔥', descEn: 'Pinned status for friends', descUa: 'Закріплений статус у друзів' },
  { id: 'themes', nameEn: 'Custom Themes', nameUa: 'Теми', price: 350, icon: '🎨', descEn: 'Midnight & Emerald UI', descUa: 'Темна та Смарагдова теми' },
  { id: 'insights', nameEn: 'Safe Insights', nameUa: 'Аналітика', price: 250, icon: '📊', descEn: 'Weekly safety reports', descUa: 'Тижневі звіти безпеки' },
  { id: 'legacy', nameEn: 'Legacy Badge', nameUa: 'Значок Ветерана', price: 100, icon: '🏅', descEn: 'Permanent status icon', descUa: 'Постійний значок статусу' }
];

export const TRANSLATIONS: AppTranslations = {
  [Language.EN]: {
    appName: "I'm Okay!",
    checkInButton: "I'm Okay!",
    checkedIn: "Check-in Complete!",
    points: "Points",
    streak: "Streak",
    friends: "Friends",
    chat: "Messages",
    settings: "Settings",
    language: "Language",
    emergencyAlert: "Emergency!",
    lastSeen: "Last seen",
    hoursAgo: "h ago",
    now: "now",
    aiSuggestion: "AI Thought",
    encouragement: "Stay safe, stay connected.",
    friendStatusSafe: "Safe",
    friendStatusWarning: "Warning",
    friendStatusAlert: "Alert",
    addFriend: "Add Friend",
    dashboard: "Home",
    friendRequests: "Requests",
    accept: "Accept",
    decline: "Decline",
    noRequests: "No requests",
    simulateRequest: "Mock",
    notifications: "Notifications",
    testEmergency: "Test Alert",
    newFriendRequest: "New Request",
    emergencyWarning: "hasn't checked in!",
    welcomeMessage: "Welcome back",
    loginGoogle: "Google",
    loginFacebook: "Facebook",
    loginApple: "Apple",
    signOut: "Log Out",
    authTagline: "Stay safe together.",
    setMood: "Mood",
    call: "Call",
    chooseCallMethod: "Call via",
    linkedMessengers: "Messengers",
    phone: "Phone",
    facebook: "Facebook",
    telegram: "Telegram",
    whatsapp: "WhatsApp",
    viber: "Viber",
    save: "Save",
    editProfile: "Profile",
    vipStatus: "VIP Perk",
    level: "Level",
    coins: "Coins",
    levelUp: "Level Up!",
    getVip: "Get VIP",
    vipBenefits: "Earn 2x Coins",
    xp: "XP",
    inviteFriend: "Invite",
    inviteMsg: (name) => `${name} is worried! Download 'I'm Okay!': im-okay.app`,
    fromContacts: "Contacts",
    manualInvite: "Manual",
    enterPhoneOrSocial: "Enter info",
    shop: "Shop",
    buy: "Unlock",
    unlocked: "Owned",
    notEnoughCoins: "Insufficient coins",
    insufficientFunds: "You need more coins!",
    exportProject: "Download Project",
    backupDesc: "Save all files for GitHub"
  },
  [Language.UA]: {
    appName: "Я в порядку!",
    checkInButton: "Я в порядку!",
    checkedIn: "Відмітка зроблена!",
    points: "Бали",
    streak: "Серія",
    friends: "Друзі",
    chat: "Чати",
    settings: "Налаштування",
    language: "Мова",
    emergencyAlert: "Тривога!",
    lastSeen: "Востаннє",
    hoursAgo: "г. тому",
    now: "щойно",
    aiSuggestion: "Думка ШІ",
    encouragement: "Бережіть себе та близьких.",
    friendStatusSafe: "В нормі",
    friendStatusWarning: "Увага",
    friendStatusAlert: "Тривога",
    addFriend: "Додати",
    dashboard: "Головна",
    friendRequests: "Запити",
    accept: "Так",
    decline: "Ні",
    noRequests: "Немає",
    simulateRequest: "Тест",
    notifications: "Сповіщення",
    testEmergency: "Сигнал",
    newFriendRequest: "Запит",
    emergencyWarning: "не відмітився!",
    welcomeMessage: "З поверненням",
    loginGoogle: "Google",
    loginFacebook: "Facebook",
    loginApple: "Apple",
    signOut: "Вихід",
    authTagline: "Будьмо в безпеці разом.",
    setMood: "Настрій",
    call: "Дзвінок",
    chooseCallMethod: "Дзвонити через",
    linkedMessengers: "Месенджери",
    phone: "Телефон",
    facebook: "Facebook",
    telegram: "Telegram",
    whatsapp: "WhatsApp",
    viber: "Viber",
    save: "Зберегти",
    editProfile: "Профіль",
    vipStatus: "VIP Бонус",
    level: "Рівень",
    coins: "Монети",
    levelUp: "Новий уровень!",
    getVip: "Активувати VIP",
    vipBenefits: "x2 монет щодня",
    xp: "Досвід",
    inviteFriend: "Запросити",
    inviteMsg: (name) => `${name} переживає! Додайся в додаток 'Я в порядку!': im-okay.app`,
    fromContacts: "Контакти",
    manualInvite: "Ручно",
    enterPhoneOrSocial: "Введіть дані",
    shop: "Магазин",
    buy: "Придбати",
    unlocked: "Куплено",
    notEnoughCoins: "Мало монет",
    insufficientFunds: "Вам не вистачає монет!",
    exportProject: "Завантажити проект",
    backupDesc: "Зберегти файли для GitHub"
  }
};

export const SHARE_TRANSLATIONS = {
  [Language.EN]: {
    shareTitle: "My Status",
    sharePreview: "Preview",
    shareMessage: (name: string, mood: string, streakText: string) => `I'm Okay! ${streakText} streak. Check me: im-okay.app/p/${name}`,
    shareAction: "Share",
    copyLink: "Copy",
    copied: "Copied!",
    imSafe: "I am safe!",
    days: "Days",
    weeks: "Weeks",
    months: "Months",
    years: "Years"
  },
  [Language.UA]: {
    shareTitle: "Мій статус",
    sharePreview: "Перегляд",
    shareMessage: (name: string, mood: string, streakText: string) => `Я в порядку! Вже ${streakText} поспіль. Мій статус: im-okay.app/p/${name}`,
    shareAction: "Поділитися",
    copyLink: "Копіювати",
    copied: "ОК!",
    imSafe: "Я в безпеці!",
    days: "Днів",
    weeks: "Тижнів",
    months: "Місяців",
    years: "Років"
  }
};