import { AppTranslations, Language } from './types';

export const CHECKIN_TIMEOUT_WARNING = 24 * 60 * 60 * 1000;
export const CHECKIN_TIMEOUT_ALERT = 48 * 60 * 60 * 1000;

export const SHOP_ITEMS = [
  { id: 'ghost', nameEn: 'Ghost Mode', nameUa: 'Режим Привида', price: 500, icon: '👻', descEn: 'Hide status from others', descUa: 'Приховати статус від інших' },
  { id: 'extended', nameEn: '72h Window', nameUa: 'Вікно 72г', price: 1000, icon: '⏳', descEn: 'Alert friends after 72h', descUa: 'Тривога через 72г' },
  { id: 'gold', nameEn: 'Gold Profile', nameUa: 'Золотий Профіль', price: 300, icon: '✨', descEn: 'Animated golden border', descUa: 'Анімована золота рамка' },
  { id: 'guardian', nameEn: 'AI Guardian', nameUa: 'AI Охоронець', price: 600, icon: '🛡️', descEn: 'Daily AI safety tips', descUa: 'Щоденні поради від ШІ' }
];

export const TRANSLATIONS: AppTranslations = {
  [Language.EN]: {
    appName: "I'm Okay!",
    checkInButton: "I'm Okay!",
    checkedIn: "Check-in Complete!",
    points: "Points",
    streak: "Streak",
    friends: "Friends",
    chat: "Messages",
    settings: "Settings",
    language: "Language",
    emergencyAlert: "Emergency!",
    lastSeen: "Last seen",
    hoursAgo: "h ago",
    now: "now",
    aiSuggestion: "AI Thought",
    encouragement: "Stay safe, stay connected.",
    friendStatusSafe: "Safe",
    friendStatusWarning: "Warning",
    friendStatusAlert: "Alert",
    addFriend: "Add Friend",
    dashboard: "Home",
    friendRequests: "Requests",
    accept: "Accept",
    decline: "Decline",
    noRequests: "No requests",
    simulateRequest: "Mock",
    notifications: "Notifications",
    testEmergency: "Test Alert",
    newFriendRequest: "New Request",
    emergencyWarning: "hasn't checked in!",
    welcomeMessage: "Welcome back",
    loginGoogle: "Google",
    loginFacebook: "Facebook",
    loginApple: "Apple",
    signOut: "Log Out",
    authTagline: "Stay safe together.",
    setMood: "Mood",
    call: "Call",
    chooseCallMethod: "Call via",
    linkedMessengers: "Messengers",
    phone: "Phone",
    facebook: "Facebook",
    telegram: "Telegram",
    whatsapp: "WhatsApp",
    viber: "Viber",
    save: "Save",
    editProfile: "Profile",
    vipMember: "VIP Member",
    level: "Level",
    coins: "Coins",
    levelUp: "Level Up!",
    becomeVip: "Get VIP",
    vipBenefits: "x2 Coins daily"
  },
  [Language.UA]: {
    appName: "Я в порядку!",
    checkInButton: "Я в порядку!",
    checkedIn: "Відмітка зроблена!",
    points: "Бали",
    streak: "Серія",
    friends: "Друзі",
    chat: "Чати",
    settings: "Налаштування",
    language: "Мова",
    emergencyAlert: "Тривога!",
    lastSeen: "Востаннє",
    hoursAgo: "г. тому",
    now: "щойно",
    aiSuggestion: "Думка ШІ",
    encouragement: "Бережіть себе та близьких.",
    friendStatusSafe: "В нормі",
    friendStatusWarning: "Увага",
    friendStatusAlert: "Тривога",
    addFriend: "Додати",
    dashboard: "Головна",
    friendRequests: "Запити",
    accept: "Так",
    decline: "Ні",
    noRequests: "Немає",
    simulateRequest: "Тест",
    notifications: "Сповіщення",
    testEmergency: "Сигнал",
    newFriendRequest: "Запит",
    emergencyWarning: "не відмітився!",
    welcomeMessage: "З поверненням",
    loginGoogle: "Google",
    loginFacebook: "Facebook",
    loginApple: "Apple",
    signOut: "Вихід",
    authTagline: "Будьмо в безпеці разом.",
    setMood: "Настрій",
    call: "Дзвінок",
    chooseCallMethod: "Дзвонити через",
    linkedMessengers: "Месенджери",
    phone: "Телефон",
    facebook: "Facebook",
    telegram: "Telegram",
    whatsapp: "WhatsApp",
    viber: "Viber",
    save: "Зберегти",
    editProfile: "Профіль",
    vipMember: "VIP Учасник",
    level: "Рівень",
    coins: "Монети",
    levelUp: "Новий рівень!",
    becomeVip: "Стати VIP",
    vipBenefits: "x2 монет щодня"
  }
};

export const SHARE_TRANSLATIONS = {
  [Language.EN]: {
    shareTitle: "My Safety Status",
    shareMessage: (name: string, mood: string, streak: string) => `I'm Okay! My current streak is ${streak}. Mood: ${mood}`,
    shareAction: "Share",
    copyLink: "Copy Link",
    copied: "Copied!",
    imSafe: "I am safe!",
    days: "Days",
    weeks: "Weeks",
    months: "Months",
    years: "Years"
  },
  [Language.UA]: {
    shareTitle: "Мій статус безпеки",
    shareMessage: (name: string, mood: string, streak: string) => `Я в порядку! Моя серія становить ${streak}. Настрій: ${mood}`,
    shareAction: "Поділитися",
    copyLink: "Копіювати",
    copied: "Копійовано!",
    imSafe: "Я в безпеці!",
    days: "Днів",
    weeks: "Тижнів",
    months: "Місяців",
    years: "Років"
  }
};